# Generated by Django 2.1.5 on 2019-01-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20190116_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sumstuff',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
