# Generated by Django 2.1.5 on 2019-01-17 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_profile_sumstuff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='sumstuff',
        ),
    ]
