# Generated by Django 2.1.5 on 2019-01-17 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_profile_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='some_things',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
