# Generated by Django 2.1.5 on 2019-01-17 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20190117_1018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='following',
            new_name='something',
        ),
    ]
