# Generated by Django 2.1.5 on 2019-01-21 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_auto_20190117_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='something',
        ),
    ]
