# Generated by Django 2.1.5 on 2019-01-21 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_remove_profile_something'),
        ('profiles', '0007_remove_profile_sumstuff'),
    ]

    operations = [
    ]
