# Generated by Django 2.1.5 on 2019-01-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_merge_20190121_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_notification_permissions',
            field=models.BooleanField(default=False),
        ),
    ]
