# Generated by Django 2.1.5 on 2019-01-31 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_auto_20190130_1248'),
        ('profiles', '0016_remove_readingstat_total_read_time'),
    ]

    operations = [
    ]
