# Generated by Django 2.1.5 on 2019-01-15 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20190115_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='favouriteCount',
        ),
        migrations.RemoveField(
            model_name='article',
            name='favourited',
        ),
    ]
