# Generated by Django 2.1.5 on 2019-01-21 13:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20190117_0556'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(max_length=255), default=list, size=None),
        ),
    ]
