# Generated by Django 2.1.5 on 2019-01-22 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_auto_20190121_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='read_time',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='images',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
