# Generated by Django 2.1.5 on 2019-01-21 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_auto_20190121_1401'),
        ('articles', '0011_auto_20190121_1432'),
    ]

    operations = [
    ]
