# Generated by Django 2.1.5 on 2019-01-22 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_auto_20190122_1422'),
        ('articles', '0012_auto_20190122_0826'),
    ]

    operations = [
    ]
