# Generated by Django 2.1.5 on 2019-01-22 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='user_rating',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
