# Generated by Django 2.1.5 on 2019-01-22 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_article_user_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='user_rating',
        ),
    ]
