# Generated by Django 2.1.5 on 2019-01-22 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_auto_20190122_0826'),
        ('articles', '0014_auto_20190121_1631'),
    ]

    operations = [
    ]
