# Generated by Django 2.1.5 on 2019-01-23 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_merge_20190122_1103'),
        ('articles', '0012_auto_20190122_0636'),
    ]

    operations = [
    ]
