# Generated by Django 2.1.5 on 2019-01-23 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_merge_20190122_1103'),
        ('articles', '0013_merge_20190122_1343'),
    ]

    operations = [
    ]
