# Generated by Django 2.1.5 on 2019-01-23 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_merge_20190123_0814'),
        ('articles', '0016_merge_20190123_0702'),
    ]

    operations = [
    ]
