# Generated by Django 2.1.5 on 2019-01-23 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_auto_20190122_1817'),
        ('articles', '0016_merge_20190123_0814'),
    ]

    operations = [
    ]
