# Generated by Django 2.1.5 on 2019-01-23 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_merge_20190123_1105'),
        ('articles', '0017_merge_20190123_0856'),
    ]

    operations = [
    ]
