# Generated by Django 2.1.5 on 2019-01-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_articlelikes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlelikes',
            name='article_like',
            field=models.BooleanField(null=True),
        ),
    ]
