# Generated by Django 2.1.5 on 2019-01-23 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0018_merge_20190123_1319'),
        ('articles', '0017_auto_20190123_1002'),
    ]

    operations = [
    ]
