# Generated by Django 2.1.5 on 2019-01-23 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0018_auto_20190123_1145'),
        ('articles', '0018_merge_20190123_1319'),
    ]

    operations = [
    ]
