# Generated by Django 2.1.5 on 2019-01-23 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0018_merge_20190123_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favourite', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='favouriteCount',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='favourited',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='favourites',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_id', to='articles.Article'),
        ),
        migrations.AddField(
            model_name='favourites',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
