# Generated by Django 2.1.5 on 2019-01-28 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0019_auto_20190123_1830'),
        ('articles', '0019_rating'),
    ]

    operations = [
    ]
