# Generated by Django 2.1.5 on 2019-01-29 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0020_merge_20190128_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favourites',
            old_name='user',
            new_name='author',
        ),
    ]
