# Generated by Django 2.1.5 on 2019-01-30 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0020_articledislikes_articlelikes'),
        ('articles', '0024_auto_20190130_0421'),
    ]

    operations = [
    ]
