# Generated by Django 2.1.5 on 2019-01-30 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0021_auto_20190129_1221'),
        ('articles', '0025_merge_20190130_0506'),
    ]

    operations = [
    ]
