# Generated by Django 2.1.5 on 2019-01-29 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_likecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='end_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='selected_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='start_index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
