# Generated by Django 2.1.5 on 2019-02-19 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_edithistory'),
        ('comments', '0004_auto_20190129_0954'),
    ]

    operations = [
    ]
